name: Jumbo Price Scraper

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Python dependencies
        run: |
          pip install selenium webdriver-manager gspread google-auth-oauthlib pandas

      - name: Run Scraper
        env:
          GSPREAD_CREDENTIALS: ${{ secrets.GSPREAD_CREDENTIALS }}
        run: python main.py

      # --- ¡NUEVO PASO IMPORTANTE AQUÍ! ---
      # Sube cualquier archivo .png (nuestras capturas) como un artefacto.
      # Este paso se ejecutará siempre, incluso si el paso anterior falla.
      - name: Upload error screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: error-screenshots
          path: ./*.png
