name: Jumbo Price Scraper

on:
  # Programa la ejecución todos los lunes a las 12:00 UTC. Ajusta según necesidad.
  schedule:
    - cron: '0 12 * * 1'
  # Permite ejecutar manualmente desde la interfaz de GitHub.
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          # Instalamos las dependencias necesarias para el scraper
          pip install requests beautifulsoup4 gspread google-auth-oauthlib pandas

      - name: Run Scraper
        env:
          # Credenciales para Google Sheets
          GSPREAD_CREDENTIALS: ${{ secrets.GSPREAD_CREDENTIALS }}
          # Clave de la API de ScrapingAnt definida en los secretos del repositorio
          SCRAPINGANT_API_KEY: ${{ secrets.SCRAPINGANT_API_KEY }}
        run: python main.py
